bag_of_tokens/api/urls.py
from django.urls import include, path

from api.views import BagListViewSet, StatisticViewSet

app_name = 'api_v1'

urlpatterns = [
    path(
        'bag/',
        BagListViewSet.as_view({'get': 'list'}),
        name='bag'
    ),
    path(
        'random/',
        BagListViewSet.as_view({'get': 'retrieve'}),
        name='random'
    ),
    path(
        'add/',
        BagListViewSet.as_view({'post': 'create'}),
        name='add'
    ),
    path(
        'delete/',
        BagListViewSet.as_view({'delete': 'destroy'}),
        name='delete'
    ),
    path(
        'statistic/',
        StatisticViewSet.as_view({'get': 'retrieve'}),
        name='statistic'
    ),
    path('', include('djoser.urls.jwt')),
    path('', include('djoser.urls')),
]

bag_of_tokens/bag/urls.py
from django.urls import path

from .views import AddToken, DeleteToken, RandomToken

app_name = 'bag'

urlpatterns = [
    path('add/', AddToken.as_view(), name='add'),
    path('delete/<int:pk>', DeleteToken.as_view(), name='delete'),
    path('random/', RandomToken.as_view(), name='random')
]

bag_of_tokens/bag_of_tokens/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path, reverse_lazy
from django.views.generic import TemplateView
from django.views.generic.edit import CreateView

from users.forms import UserRegistrationForm

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('django.contrib.auth.urls')),
    path('auth/registration/',
         CreateView.as_view(
             template_name='registration/registration_form.html',
             form_class=UserRegistrationForm,
             success_url=reverse_lazy('about'),
         ),
         name='registration'),
    path('profile/', include('users.urls')),
    path('bag/', include('bag.urls')),
    path('api/v1/', include('api.urls')),
    path('', TemplateView.as_view(template_name='pages/about.html'),
         name='about'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

bag_of_tokens/users/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from . import views

app_name = 'users'

urlpatterns = [
    path('',
         views.ProfileListView.as_view(),
         name='profile'),
    path('edit_profile',
         views.ProfileUpdateView.as_view(),
         name='edit_profile'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bag_of_tokens/templates/includes/footer.html
<footer class="border-top text-center py-3">
  <p>Мешок для игры карточный ужас Аркхэма</p>    
</footer>

bag_of_tokens/templates/includes/header.html
{% load static %}
<header>
  <nav class="navbar navbar-light" style="background-color: lightskyblue">
    <div class="container">
      <a class="navbar-brand" href="{% url 'about' %}">
        <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
        Мешочек
      </a>
      {% with request.resolver_match.view_name as view_name %}
          {% if user.is_authenticated %}
            <div class="btn-group" role="group" aria-label="Basic outlined example">
              <button type="button" class="btn btn-outline-primary"><a class="text-decoration-none text-reset"
                  href="{% url 'users:profile' %}">{{ user.username }}</a></button>
              <button type="button" class="btn btn-outline-primary"><a class="text-decoration-none text-reset"
                  href="{% url 'logout' %}">Выйти</a></button>
            </div>
          {% else %}
            <div class="btn-group" role="group" aria-label="Basic outlined example">
              <button type="button" class="btn btn-outline-primary"><a class="text-decoration-none text-reset"
                  href="{% url 'login' %}">Войти</a></button>
              <button type="button" class="btn btn-outline-primary"><a class="text-decoration-none text-reset"
                  href="{% url 'registration' %}">Регистрация</a></button>
            </div>
          {% endif %} 
        </ul>
      {% endwith %}
    </div>
  </nav>
</header>

bag_of_tokens/templates/includes/token_card.html
{% load static %}
<div>
  <img src="{% static token.token.image %}">
  <a href="{% url 'bag:delete' token.id %}"> Удалить жетон </a>
</div>