bag_of_tokens/api/urls.py
from django.urls import include, path

from api.views import BagListViewSet, StatisticViewSet

app_name = 'api_v1'

urlpatterns = [
    path(
        'bag/',
        BagListViewSet.as_view({'get': 'list'}),
        name='bag'
    ),
    path(
        'random/',
        BagListViewSet.as_view({'get': 'retrieve'}),
        name='random'
    ),
    path(
        'add/',
        BagListViewSet.as_view({'post': 'create'}),
        name='add'
    ),
    path(
        'delete/',
        BagListViewSet.as_view({'delete': 'destroy'}),
        name='delete'
    ),
    path(
        'statistic/',
        StatisticViewSet.as_view({'get': 'retrieve'}),
        name='statistic'
    ),
    path('', include('djoser.urls.jwt')),
    path('', include('djoser.urls')),
]

bag_of_tokens/bag/urls.py
from django.urls import path

from .views import AddToken, DeleteToken, RandomToken

app_name = 'bag'

urlpatterns = [
    path('add/', AddToken.as_view(), name='add'),
    path('delete/<int:pk>', DeleteToken.as_view(), name='delete'),
    path('random/', RandomToken.as_view(), name='random')
]

bag_of_tokens/bag_of_tokens/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path, reverse_lazy
from django.views.generic import TemplateView
from django.views.generic.edit import CreateView

from users.forms import UserRegistrationForm

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('django.contrib.auth.urls')),
    path('auth/registration/',
         CreateView.as_view(
             template_name='registration/registration_form.html',
             form_class=UserRegistrationForm,
             success_url=reverse_lazy('about'),
         ),
         name='registration'),
    path('profile/', include('users.urls')),
    path('bag/', include('bag.urls')),
    path('api/v1/', include('api.urls')),
    path('', TemplateView.as_view(template_name='pages/about.html'),
         name='about'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

bag_of_tokens/users/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from . import views

app_name = 'users'

urlpatterns = [
    path('',
         views.ProfileListView.as_view(),
         name='profile'),
    path('edit_profile',
         views.ProfileUpdateView.as_view(),
         name='edit_profile'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bag_of_tokens/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class MyUser(AbstractUser):
    email = models.EmailField(
        verbose_name='Электронная почта',
        blank=True)
    telegram_id = models.CharField(
        verbose_name='Телеграм id',
        max_length=20,
        unique=True,
    )
    is_telegram_bot = models.BooleanField(
        verbose_name='Это телеграм бот?',
        default=False
    )

    REQUIRED_FIELDS = [
        'telegram_id',
    ]

    class Meta:
        verbose_name = 'пользователь'
        verbose_name_plural = 'Пользователи'

    def __str__(self):
        return self.username

bag_of_tokens/users/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

User = get_user_model()


class UserRegistrationForm(UserCreationForm):

    class Meta:
        model = User
        fields = (
            'username',
            'email',
            'telegram_id',
            'password1',
            'password2',
        )

bag_of_tokens/users/views.py
from django.contrib.auth import get_user_model
from django.shortcuts import get_object_or_404
from django.urls import reverse
from django.views.generic import DetailView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin

from bag.models import Bag

User = get_user_model()


class ProfileListView(LoginRequiredMixin, DetailView):
    model = User
    fields = ('username', 'first_name', 'last_name', 'email', 'telegram_id',)
    template_name = 'user/profile.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['tokens'] = Bag.objects.filter(owner=self.request.user).select_related('token')
        return context

    def get_object(self):
        return self.request.user


class ProfileUpdateView(LoginRequiredMixin, UpdateView):
    model = User
    fields = ('username', 'first_name', 'last_name', 'email', 'telegram_id',)
    template_name = 'user/update_profile.html'

    def get_object(self):
        return get_object_or_404(
            User,
            username=self.request.user.username,
        )

    def get_success_url(self):
        return reverse('users:profile')

bag_of_tokens/templates/user/profile.html
{% extends "base.html" %}
{% load static %}
{% block title %}
  Страница пользователя {{ object.username }}
{% endblock %}
{% block content %}
  <h1 class="mb-5 text-center ">Страница пользователя {{ object.username }}</h1>
  <small>
    <ul class="list-group list-group-horizontal justify-content-center mb-3">
      <li class="list-group-item text-muted">Имя пользователя: {% if object.get_full_name %}{{ object.get_full_name }}{% else %}не указано{% endif %}</li>
      <li class="list-group-item text-muted">Регистрация: {{ object.date_joined }}</li>
      <li class="list-group-item text-muted">Телеграм id: {% if object.telegram_id %}{{ object.telegram_id }}{% else %}не указано{% endif %}</li>
    </ul>
    <ul class="list-group list-group-horizontal justify-content-center">
      <a class="btn btn-sm text-muted" href="{% url 'users:edit_profile' %}">Редактировать профиль</a>
      <a class="btn btn-sm text-muted" href="{% url 'password_change' %}">Изменить пароль</a>
    </ul>
  </small>
   <br>
  <h3 class="mb-5 text-center">Ваш мешок</h3>
  <h3 class="mb-5 text-center"> <a href="{% url 'bag:random' %}"> Достать жетон </a> </h3>
  <div style="display: inline-block">
    {% if tokens %}
      {% for token in tokens %}
        {% include "includes/Token_card.html" %}
      {% endfor %}
    {% else %}
      Мешок пуст </p>
    {% endif %}
    <a href="{% url 'bag:add' %}">
      <img src="{% static 'img/new.png' %}" title="Добавить новый жетон">
    </a>
  </div>
{% endblock %}

bag_of_tokens/templates/user/update_profile.html
{% extends "base.html" %}
{% load django_bootstrap5 %}
{% block title %}
  Редактирование профиля
{% endblock %}
{% block content %}
  <div class="col d-flex justify-content-center">
    <div class="card" style="width: 40rem;">
      <div class="card-header">
        Редактирование профиля - {{ request.user.username }}
      </div>
      <div class="card-body">
        <form method="post">
          {% csrf_token %}
          {% bootstrap_form form %}
          {% bootstrap_button button_type="submit" content="Отправить" %}
        </form>
      </div>
    </div>
  </div>
{% endblock %}